name: API testing

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string
        description: Environment to run tests against (e.g., dev, staging, prod)
        default: dev

      api_version:
        description: 'API Version'
        required: false
        type: string
        default: v1

jobs:
  TestAPI:
    name: Test API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: List directory structure
        run: ls -R

      - name: Run API Tests
        working-directory: src/testAPI # Adjust this if the directory is elsewhere
        run: |
          mvn -q testAPI -Denv=${{ github.event.inputs.environment }} -Dapi.version=${{ github.event.inputs.api_version }}
