name: API testing

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string
        description: Environment to run tests against (e.g., dev, staging, prod)
        default: dev

      api_version:
        description: 'API Version'
        required: false
        type: string
        default: v1

jobs:
  TestAPI:
    name: Test API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Set environment variables
        run: |
          export ENVIRONMENT=${{ github.event.inputs.environment }}
          export API_VERSION=${{ github.event.inputs.api_version }}
          echo "ENVIRONMENT=${ENVIRONMENT}" >> $GITHUB_ENV
          echo "API_VERSION=${API_VERSION}" >> $GITHUB_ENV

      - name: Run API Tests
        run: |
          mvn -q testAPI 
